### PR TITLE
Challenge list

### PR DESCRIPTION
**Pull request by uttpal**

### CODE REVIEW

**Comment by mukuljainx** [comment]
getting 401 error, on Challenge list API call even after login.

**Comment by uttpal** [comment]
Code is bit outdated on backend, i will update it

**Comment by uttpal** [comment]
should work now

**Comment by mukuljainx** [comment]
If we are fixing character limit in challenge preview para and limited tags? like 300 char for preview and displaying max 4/8 out of n tags on list page.
we can fix their div's height to make every card look same.

**Comment by uttpal** [comment]
yes that would work better., merge this then will do that

**Pull request merged**
